# kubectl apply -f k8s.service.ingress.yaml
# kubectl get services
# kubectl delete ingress.networking.k8s.io/demo-service-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-service-ingress
spec:
  rules:
  - host: "localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demo-service # Name of your Service
            port:
              number: 8083